services:
  postgres:
    container_name: pycon-cta-pg
    build:
      context: ./db
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5442:5442
    networks:
      - pycon-cta-nw
  proxy:
    container_name: pycon-cta-proxy
    image: cipherstash/cipherstash-proxy:cipherstash-proxy-v0.3.5
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${CS_PORT:-6432}:${CS_PORT:-6432}
    environment:
      CS_WORKSPACE_ID: $CS_WORKSPACE_ID
      CS_CLIENT_ACCESS_KEY: $CS_CLIENT_ACCESS_KEY
      CS_ENCRYPTION__CLIENT_ID: $CS_ENCRYPTION__CLIENT_ID
      CS_ENCRYPTION__CLIENT_KEY: $CS_ENCRYPTION__CLIENT_KEY
      CS_ENCRYPTION__DATASET_ID: $CS_DATASET_ID
      CS_TEST_ON_CHECKOUT: "true"
      CS_AUDIT__ENABLED: "false"
      CS_DATABASE__PORT: 5432
      CS_DATABASE__USERNAME: postgres
      CS_DATABASE__PASSWORD: postgres
      CS_DATABASE__NAME: postgres
      CS_DATABASE__HOST: pycon-cta-pg
      CS_UNSAFE_LOGGING: "true"
    networks:
      - pycon-cta-nw

networks:
  pycon-cta-nw:
    driver: bridge
